name: RPC_IDL_UPDATE
on:
  push:
    branches: [ "*" ]
    paths:
      - 'rpc_idl/**'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Kitex Gen
        run: |
          branch=$(echo ${{ github.event.ref }} | awk -F '/' '{print $3}')
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/nas-studying/idl_gen/dispatches \
          -d '{"event_type":"idl_update","client_payload":{"repository":"${{ github.repository }}","ref":"'$branch'","commit_msg":"${{ github.event.head_commit.message }}"}}'
